/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/doctor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Doctor
         * @description The standing checks, rendered instead of read from a terminal.
         *
         *     Deliberately the same `run_doctor` the CLI calls. It tokenizes candidate
         *     chunks with the real tokenizer, so this is not a free request — it is a
         *     diagnostic somebody asked for, not something to poll.
         */
        get: operations["get_doctor_doctor_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/judgements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Judgements
         * @description One row per judged query, so the golden set can be watched as it grows.
         */
        get: operations["list_judgements_judgements_get"];
        put?: never;
        /**
         * Create Judgement
         * @description Record a verdict, replacing any previous one for the same query and item.
         */
        post: operations["create_judgement_judgements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/judgements/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export
         * @description The golden set as JSON. M2.0's direct input.
         *
         *     Untyped `dict` on purpose: this is a data interchange format whose consumer
         *     is an evaluation harness that does not exist yet, and pinning it into a
         *     response model now would be inventing a contract for it.
         */
        get: operations["export_judgements_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Memories */
        get: operations["list_memories_memories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memories/{memory_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Memory */
        get: operations["get_memory_memories__memory_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_search_get"];
        put?: never;
        /**
         * Search Post
         * @description Same thing, for queries too long to sit comfortably in a URL.
         */
        post: operations["search_post_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sources
         * @description Every source, with how much of the corpus came from it.
         *
         *     Outer-joined and grouped rather than a count per source in a loop: the list
         *     is short today, but a query per row is the shape that stops being fine
         *     without anybody noticing.
         */
        get: operations["list_sources_sources_get"];
        put?: never;
        /** Create Source */
        post: operations["create_source_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{source_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Sync
         * @description Enqueue a sync. Never runs it inline.
         *
         *     A sync of a large directory takes minutes. Running it in the request would
         *     blow the HTTP timeout, and whatever it managed to do would have no retry,
         *     no progress, and no way to resume. 202 with a job id is the honest answer.
         */
        post: operations["trigger_sync_sources__source_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BreakdownOut
         * @description Where the score came from, per retriever.
         *
         *     Returned on every hit in every mode. Once two retrievers are fused into one
         *     number, that number is the only thing a client can show, and without this it
         *     cannot say *why* — which is both how a bad ranking gets debugged and what
         *     M2.5's citations will render. A null rank means that retriever did not
         *     return the chunk, which is not the same as returning it last.
         */
        BreakdownOut: {
            /** Fused */
            fused: number;
            /** Keyword Rank */
            keyword_rank?: number | null;
            /** Keyword Score */
            keyword_score?: number | null;
            /** Vector Rank */
            vector_rank?: number | null;
            /** Vector Score */
            vector_score?: number | null;
        };
        /** CreateSource */
        CreateSource: {
            /** Exclude */
            exclude?: string[] | null;
            /**
             * Follow Symlinks
             * @default false
             */
            follow_symlinks: boolean;
            /** Include */
            include?: string[] | null;
            /** @default filesystem */
            kind: components["schemas"]["SourceKind"];
            /** Max File Bytes */
            max_file_bytes?: number | null;
            /** Name */
            name: string;
            /** Root */
            root: string;
        };
        /** DoctorOut */
        DoctorOut: {
            /** Chunker Version */
            chunker_version: string;
            /** Embedding Model */
            embedding_model: string;
            /** Findings */
            findings: components["schemas"]["FindingOut"][];
            /** Healthy */
            healthy: boolean;
            /** Model Window */
            model_window: number;
        };
        /** FindingOut */
        FindingOut: {
            /** Check */
            check: string;
            /** Count */
            count: number;
            /** Detail */
            detail: string;
            /** Examples */
            examples: string[];
            /** Healthy */
            healthy: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HitOut */
        HitOut: {
            /** External Key */
            external_key: string;
            /** Kind */
            kind: string;
            /** Matched Chunks */
            matched_chunks: components["schemas"]["memoryos__api__routes__search__ChunkOut"][];
            /**
             * Memory Id
             * Format: uuid
             */
            memory_id: string;
            /** Occurred At */
            occurred_at: string | null;
            /** Score */
            score: number;
            /** Source Name */
            source_name: string;
            /** Title */
            title: string | null;
        };
        /** JudgementIn */
        JudgementIn: {
            /** Chunk Id */
            chunk_id?: string | null;
            /** Chunk Ordinal */
            chunk_ordinal?: number | null;
            /** External Key */
            external_key: string;
            /** Filters */
            filters?: {
                [key: string]: unknown;
            };
            /** Memory Id */
            memory_id?: string | null;
            /** Query Text */
            query_text: string;
            /** Rank At Judgement */
            rank_at_judgement?: number | null;
            /** Score At Judgement */
            score_at_judgement?: number | null;
            /** Source Name */
            source_name: string;
            verdict: components["schemas"]["Verdict"];
        };
        /** JudgementOut */
        JudgementOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** Liveness */
        Liveness: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** MemoryDetailOut */
        MemoryDetailOut: {
            /** Chunks */
            chunks: components["schemas"]["memoryos__api__routes__memories__ChunkOut"][];
            /** Content */
            content: string | null;
            /** Content Hash */
            content_hash: string;
            /** Deleted At */
            deleted_at: string | null;
            /** External Key */
            external_key: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Ingested At
             * Format: date-time
             */
            ingested_at: string;
            /** Is Current */
            is_current: boolean;
            /** Kind */
            kind: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Normalized Hash */
            normalized_hash: string | null;
            /** Occurred At */
            occurred_at: string | null;
            /** Occurred At Source */
            occurred_at_source: string;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /** Source Name */
            source_name: string;
            /** Title */
            title: string | null;
            /** Version */
            version: number;
            /** Versions */
            versions: components["schemas"]["VersionOut"][];
        };
        /**
         * MemoryKind
         * @enum {string}
         */
        MemoryKind: "note" | "document" | "code" | "email" | "commit" | "meeting" | "bookmark" | "other";
        /** MemoryOut */
        MemoryOut: {
            /** Content Hash */
            content_hash: string;
            /** Deleted At */
            deleted_at: string | null;
            /** External Key */
            external_key: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Ingested At
             * Format: date-time
             */
            ingested_at: string;
            /** Is Current */
            is_current: boolean;
            /** Kind */
            kind: string;
            /** Occurred At */
            occurred_at: string | null;
            /** Occurred At Source */
            occurred_at_source: string;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /** Title */
            title: string | null;
            /** Version */
            version: number;
        };
        /** QuerySummaryOut */
        QuerySummaryOut: {
            /**
             * Last Judged At
             * Format: date-time
             */
            last_judged_at: string;
            /** Missing */
            missing: number;
            /** Not Relevant */
            not_relevant: number;
            /** Query Text */
            query_text: string;
            /** Relevant */
            relevant: number;
            /** Total */
            total: number;
        };
        /** Readiness */
        Readiness: {
            /** Database */
            database: boolean;
            /** Pgvector Version */
            pgvector_version: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
        };
        /** SearchIn */
        SearchIn: {
            /** After */
            after?: string | null;
            /** Before */
            before?: string | null;
            /** Ef Search */
            ef_search?: number | null;
            /**
             * Exact
             * @default false
             */
            exact: boolean;
            /**
             * Include Deleted
             * @default false
             */
            include_deleted: boolean;
            /**
             * K
             * @default 10
             */
            k: number;
            kind?: components["schemas"]["MemoryKind"] | null;
            /** @default hybrid */
            mode: components["schemas"]["SearchMode"];
            /** Q */
            q: string;
            /** Source */
            source?: string[] | null;
        };
        /**
         * SearchMode
         * @description Which retriever answers a query.
         *
         *     They fail in opposite directions — the vector half is blind to opaque exact
         *     tokens, the keyword half is blind to paraphrase — and M2.1 measured that
         *     complement before M2.2 fused it, so that it was possible to tell which half
         *     carries which query. `SKIP LOCKED` goes from recall 0.000 to 1.000 between
         *     them; the paraphrase queries go the other way, to exactly 0.000.
         *
         *     `HYBRID` is the product. The other two remain because the only way to know
         *     what fusion is doing is to be able to run each half alone.
         * @enum {string}
         */
        SearchMode: "vector" | "keyword" | "hybrid";
        /** SearchOut */
        SearchOut: {
            /** Hits */
            hits: components["schemas"]["HitOut"][];
            /** Query */
            query: string;
            timing: components["schemas"]["TimingOut"];
        };
        /**
         * SourceKind
         * @enum {string}
         */
        SourceKind: "filesystem";
        /** SourceOut */
        SourceOut: {
            /**
             * Chunks
             * @default 0
             */
            chunks: number;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Last Full Sync At */
            last_full_sync_at: string | null;
            /** Last Sync At */
            last_sync_at: string | null;
            /**
             * Memories
             * @default 0
             */
            memories: number;
            /** Name */
            name: string;
        };
        /** StatsOut */
        StatsOut: {
            /** Cache Entries */
            cache_entries: number;
            /** Chunker Version */
            chunker_version: string;
            /** Chunks */
            chunks: number;
            /** Coverage */
            coverage: number;
            /** Current Memories */
            current_memories: number;
            /** Embedded Chunks */
            embedded_chunks: number;
            /** Embedding Model */
            embedding_model: string;
            /** Memories */
            memories: number;
            /** Model Window */
            model_window: number;
            /** Models */
            models: {
                [key: string]: number;
            };
        };
        /** SyncAccepted */
        SyncAccepted: {
            /** Full */
            full: boolean;
            /** Job Id */
            job_id: string | null;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
        };
        /** TimingOut */
        TimingOut: {
            /** Embed Ms */
            embed_ms: number;
            /** Search Ms */
            search_ms: number;
            /** Total Ms */
            total_ms: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Verdict
         * @description What a human said about one result for one query.
         *
         *     `MISSING` is the one that carries the most information and the only one that
         *     cannot be inferred from the ranking: it names a memory that *should* have
         *     been returned and was not. Precision can be measured from the first two;
         *     recall cannot be measured from anything else.
         * @enum {string}
         */
        Verdict: "relevant" | "not_relevant" | "missing";
        /** VersionOut */
        VersionOut: {
            /** Content Hash */
            content_hash: string;
            /** Deleted At */
            deleted_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Ingested At
             * Format: date-time
             */
            ingested_at: string;
            /** Is Current */
            is_current: boolean;
            /** Normalized Hash */
            normalized_hash: string | null;
            /** Version */
            version: number;
        };
        /**
         * ChunkOut
         * @description One chunk, with the provenance that makes it auditable.
         *
         *     `char_start`/`char_end` index into the parent memory's `content`, which is
         *     what lets the UI draw boundaries on the document rather than concatenating
         *     chunk text and hoping it lines up.
         */
        memoryos__api__routes__memories__ChunkOut: {
            /** Char End */
            char_end: number;
            /** Char Start */
            char_start: number;
            /** Chunker Version */
            chunker_version: string;
            /** Content */
            content: string;
            /** Content Hash */
            content_hash: string;
            /** Embedded */
            embedded: boolean;
            /** Embedded At */
            embedded_at: string | null;
            /** Embedding Model */
            embedding_model: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Ordinal */
            ordinal: number;
            /** Token Count */
            token_count: number;
        };
        /** ChunkOut */
        memoryos__api__routes__search__ChunkOut: {
            breakdown?: components["schemas"]["BreakdownOut"] | null;
            /** Char End */
            char_end: number;
            /** Char Start */
            char_start: number;
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Ordinal */
            ordinal: number;
            /** Score */
            score: number;
            /** Text */
            text: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_doctor_doctor_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorOut"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liveness"];
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    list_judgements_judgements_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuerySummaryOut"][];
                };
            };
        };
    };
    create_judgement_judgements_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JudgementIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JudgementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_judgements_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_memories_memories_get: {
        parameters: {
            query?: {
                source_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_memory_memories__memory_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memory_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_search_get: {
        parameters: {
            query: {
                q: string;
                k?: number;
                source?: string[] | null;
                kind?: components["schemas"]["MemoryKind"] | null;
                after?: string | null;
                before?: string | null;
                include_deleted?: boolean;
                ef_search?: number | null;
                exact?: boolean;
                mode?: components["schemas"]["SearchMode"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_post_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"][];
                };
            };
        };
    };
    create_source_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSource"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_sync_sources__source_id__sync_post: {
        parameters: {
            query?: {
                full?: boolean;
            };
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOut"];
                };
            };
        };
    };
}
