"""Translation between ORM rows and domain entities.

Deliberately explicit and one-directional in each function. Domain entities do
not inherit from ORM models and carry no `to_dict()`: the moment persistence
concerns live on an entity, the domain starts depending on the store, and this
is the seam that keeps that from happening.

Columns the database fills in — `seq`, `created_at`, `first_seen_at`,
`recorded_at`, `ingested_at` — are left unset on new rows rather than assigned
`None`, so that Postgres' defaults and identity sequence apply. Assigning `None`
would send an explicit NULL and violate NOT NULL.
"""

from memoryos.adapters.db import models
from memoryos.domain.entities import (
    IngestionEvent,
    Memory,
    MemoryChunk,
    RawArtifact,
    Source,
)
from memoryos.domain.values import (
    ContentHash,
    EventType,
    MemoryKind,
    SourceKind,
    TimeProvenance,
)


def to_source(row: models.Source) -> Source:
    return Source(
        id=row.id,
        kind=SourceKind(row.kind),
        name=row.name,
        config=dict(row.config),
        cursor=dict(row.cursor),
        last_sync_at=row.last_sync_at,
        last_full_sync_at=row.last_full_sync_at,
        created_at=row.created_at,
    )


def to_source_row(source: Source) -> models.Source:
    row = models.Source(
        id=source.id,
        kind=source.kind.value,
        name=source.name,
        config=dict(source.config),
        cursor=dict(source.cursor),
        last_sync_at=source.last_sync_at,
        last_full_sync_at=source.last_full_sync_at,
    )
    if source.created_at is not None:
        row.created_at = source.created_at
    return row


def to_artifact(row: models.RawArtifact) -> RawArtifact:
    return RawArtifact(
        content_hash=ContentHash(row.content_hash),
        byte_size=row.byte_size,
        media_type=row.media_type,
        first_seen_at=row.first_seen_at,
    )


def to_artifact_row(artifact: RawArtifact) -> models.RawArtifact:
    row = models.RawArtifact(
        content_hash=artifact.content_hash.value,
        byte_size=artifact.byte_size,
        media_type=artifact.media_type,
    )
    if artifact.first_seen_at is not None:
        row.first_seen_at = artifact.first_seen_at
    return row


def to_event(row: models.IngestionEvent) -> IngestionEvent:
    return IngestionEvent(
        id=row.id,
        event_type=EventType(row.event_type),
        source_id=row.source_id,
        external_key=row.external_key,
        occurred_at_source=TimeProvenance(row.occurred_at_source),
        seq=row.seq,
        schema_version=row.schema_version,
        content_hash=None if row.content_hash is None else ContentHash(row.content_hash),
        occurred_at=row.occurred_at,
        payload=dict(row.payload),
        recorded_at=row.recorded_at,
    )


def to_event_row(event: IngestionEvent) -> models.IngestionEvent:
    row = models.IngestionEvent(
        id=event.id,
        schema_version=event.schema_version,
        event_type=event.event_type.value,
        source_id=event.source_id,
        external_key=event.external_key,
        content_hash=None if event.content_hash is None else event.content_hash.value,
        occurred_at=event.occurred_at,
        occurred_at_source=event.occurred_at_source.value,
        payload=dict(event.payload),
    )
    # Identity is GENERATED BY DEFAULT, so an explicit seq is honoured when
    # replaying or importing an existing log and omitted otherwise.
    if event.seq is not None:
        row.seq = event.seq
    if event.recorded_at is not None:
        row.recorded_at = event.recorded_at
    return row


def to_memory(row: models.Memory) -> Memory:
    return Memory(
        id=row.id,
        source_id=row.source_id,
        external_key=row.external_key,
        content_hash=ContentHash(row.content_hash),
        kind=MemoryKind(row.kind),
        occurred_at_source=TimeProvenance(row.occurred_at_source),
        version=row.version,
        is_current=row.is_current,
        normalized_hash=(
            None if row.normalized_hash is None else ContentHash(row.normalized_hash)
        ),
        title=row.title,
        content=row.content,
        occurred_at=row.occurred_at,
        ingested_at=row.ingested_at,
        importance=row.importance,
        meta=dict(row.meta),
        deleted_at=row.deleted_at,
    )


def to_memory_row(memory: Memory) -> models.Memory:
    row = models.Memory(
        id=memory.id,
        source_id=memory.source_id,
        external_key=memory.external_key,
        version=memory.version,
        is_current=memory.is_current,
        content_hash=memory.content_hash.value,
        normalized_hash=(
            None if memory.normalized_hash is None else memory.normalized_hash.value
        ),
        kind=memory.kind.value,
        title=memory.title,
        content=memory.content,
        occurred_at=memory.occurred_at,
        occurred_at_source=memory.occurred_at_source.value,
        importance=memory.importance,
        meta=dict(memory.meta),
        deleted_at=memory.deleted_at,
    )
    if memory.ingested_at is not None:
        row.ingested_at = memory.ingested_at
    return row


def to_chunk(row: models.MemoryChunk) -> MemoryChunk:
    return MemoryChunk(
        id=row.id,
        memory_id=row.memory_id,
        ordinal=row.ordinal,
        content=row.content,
        token_count=row.token_count,
        char_start=row.char_start,
        char_end=row.char_end,
        chunker_version=row.chunker_version,
        content_hash=ContentHash(row.content_hash),
        embedding=None if row.embedding is None else tuple(row.embedding),
        embedding_model=row.embedding_model,
        embedded_at=row.embedded_at,
    )


def to_chunk_row(chunk: MemoryChunk) -> models.MemoryChunk:
    return models.MemoryChunk(
        id=chunk.id,
        memory_id=chunk.memory_id,
        ordinal=chunk.ordinal,
        content=chunk.content,
        token_count=chunk.token_count,
        char_start=chunk.char_start,
        char_end=chunk.char_end,
        chunker_version=chunk.chunker_version,
        content_hash=chunk.content_hash.value,
        embedding=None if chunk.embedding is None else list(chunk.embedding),
        embedding_model=chunk.embedding_model,
        embedded_at=chunk.embedded_at,
    )
