"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-08-08

Written by hand rather than autogenerated, so that every constraint name and
CHECK expression is explicit and reviewable. `alembic revision --autogenerate`
is run afterwards as a verification step: it must produce an empty migration.

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector must exist before memory_chunks.embedding can be typed VECTOR.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "cursor",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_full_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_sources"),
        sa.UniqueConstraint("kind", "name", name="uq_sources_kind_name"),
        sa.CheckConstraint("kind IN ('filesystem')", name="ck_sources_kind"),
    )

    op.create_table(
        "raw_artifacts",
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("media_type", sa.Text(), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("content_hash", name="pk_raw_artifacts"),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'", name="ck_raw_artifacts_content_hash_hex"
        ),
        sa.CheckConstraint("byte_size >= 0", name="ck_raw_artifacts_byte_size_non_negative"),
    )

    op.create_table(
        "ingestion_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("schema_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("occurred_at_source", sa.Text(), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name="fk_ingestion_events_source_id"
        ),
        sa.ForeignKeyConstraint(
            ["content_hash"],
            ["raw_artifacts.content_hash"],
            name="fk_ingestion_events_content_hash",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_ingestion_events"),
        sa.UniqueConstraint("seq", name="uq_ingestion_events_seq"),
        sa.CheckConstraint(
            "event_type IN ('artifact_observed', 'item_deleted')",
            name="ck_ingestion_events_event_type",
        ),
        sa.CheckConstraint(
            "occurred_at_source IN ('declared', 'parsed', 'filesystem', 'inferred', 'unknown')",
            name="ck_ingestion_events_occurred_at_source",
        ),
    )
    op.create_index(
        "ix_ingestion_events_source_id_external_key",
        "ingestion_events",
        ["source_id", "external_key"],
    )
    op.create_index("ix_ingestion_events_recorded_at", "ingestion_events", ["recorded_at"])

    op.create_table(
        "memories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("is_current", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("normalized_hash", sa.Text(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("occurred_at_source", sa.Text(), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("importance", sa.REAL(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], name="fk_memories_source_id"),
        sa.ForeignKeyConstraint(
            ["content_hash"], ["raw_artifacts.content_hash"], name="fk_memories_content_hash"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_memories"),
        sa.UniqueConstraint(
            "source_id", "external_key", "version", name="uq_memories_source_key_version"
        ),
        sa.CheckConstraint("version >= 1", name="ck_memories_version_positive"),
        sa.CheckConstraint(
            "importance BETWEEN 0.0 AND 1.0", name="ck_memories_importance_range"
        ),
        # A null occurred_at is not "unknown time, use ingested_at"; it is a
        # distinct fact, and the provenance column has to say so.
        sa.CheckConstraint(
            "(occurred_at IS NULL) = (occurred_at_source = 'unknown')",
            name="ck_memories_occurred_at_provenance",
        ),
        sa.CheckConstraint(
            "kind IN ('note', 'document', 'code', 'email', 'commit', 'meeting', "
            "'bookmark', 'other')",
            name="ck_memories_kind",
        ),
        sa.CheckConstraint(
            "occurred_at_source IN ('declared', 'parsed', 'filesystem', 'inferred', 'unknown')",
            name="ck_memories_occurred_at_source",
        ),
    )
    # Exactly one current version per (source, external_key). Partial, so
    # superseded versions are free to share the pair.
    op.create_index(
        "uq_memories_current_version",
        "memories",
        ["source_id", "external_key"],
        unique=True,
        postgresql_where=sa.text("is_current"),
    )
    op.create_index("ix_memories_occurred_at", "memories", ["occurred_at"])
    op.create_index("ix_memories_ingested_at", "memories", ["ingested_at"])

    op.create_table(
        "memory_chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("memory_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("chunker_version", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.Vector(384), nullable=True),
        sa.Column("embedding_model", sa.Text(), nullable=True),
        sa.Column("embedded_at", sa.DateTime(timezone=True), nullable=True),
        # CASCADE, not RESTRICT: chunks that outlive their memory stay in the
        # vector index and keep surfacing in search results.
        sa.ForeignKeyConstraint(
            ["memory_id"],
            ["memories.id"],
            name="fk_memory_chunks_memory_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_memory_chunks"),
        sa.UniqueConstraint("memory_id", "ordinal", name="uq_memory_chunks_memory_ordinal"),
        sa.CheckConstraint("ordinal >= 0", name="ck_memory_chunks_ordinal_non_negative"),
        sa.CheckConstraint("token_count > 0", name="ck_memory_chunks_token_count_positive"),
        sa.CheckConstraint("char_start >= 0", name="ck_memory_chunks_char_start_non_negative"),
        sa.CheckConstraint("char_end > char_start", name="ck_memory_chunks_char_range"),
    )
    op.create_index("ix_memory_chunks_chunker_version", "memory_chunks", ["chunker_version"])
    op.create_index("ix_memory_chunks_content_hash", "memory_chunks", ["content_hash"])
    # No HNSW index on `embedding`. That is M1.6, built once after bulk loading
    # rather than maintained through every insert.


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_memory_chunks_content_hash", table_name="memory_chunks")
    op.drop_index("ix_memory_chunks_chunker_version", table_name="memory_chunks")
    op.drop_table("memory_chunks")

    op.drop_index("ix_memories_ingested_at", table_name="memories")
    op.drop_index("ix_memories_occurred_at", table_name="memories")
    op.drop_index(
        "uq_memories_current_version",
        table_name="memories",
        postgresql_where=sa.text("is_current"),
    )
    op.drop_table("memories")

    op.drop_index("ix_ingestion_events_recorded_at", table_name="ingestion_events")
    op.drop_index("ix_ingestion_events_source_id_external_key", table_name="ingestion_events")
    op.drop_table("ingestion_events")

    op.drop_table("raw_artifacts")
    op.drop_table("sources")
    # The `vector` extension is left installed. It is database-scoped and may be
    # shared; dropping it is not this migration's to undo.
