"""m1.1 review follow-ups

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-08

Three corrections from the M1.1 review, all of them tightening constraints that
were asymmetric or looser than the invariant they were meant to express.

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # The occurred_at/provenance pairing is universal, not specific to
    # `memories`. The system never fabricates a timestamp, so a null
    # occurred_at must say so through its provenance wherever it appears.
    op.create_check_constraint(
        "ck_ingestion_events_occurred_at_provenance",
        "ingestion_events",
        "(occurred_at IS NULL) = (occurred_at_source = 'unknown')",
    )

    # Same value object, same format guarantee as raw_artifacts.content_hash.
    op.create_check_constraint(
        "ck_memory_chunks_content_hash_hex",
        "memory_chunks",
        "content_hash ~ '^[0-9a-f]{64}$'",
    )

    # Replay reads the log to rebuild projections; it never re-inserts events.
    # Nothing has a legitimate reason to choose its own sequence, so the
    # database stops accepting one.
    op.execute("ALTER TABLE ingestion_events ALTER COLUMN seq SET GENERATED ALWAYS")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("ALTER TABLE ingestion_events ALTER COLUMN seq SET GENERATED BY DEFAULT")
    op.drop_constraint("ck_memory_chunks_content_hash_hex", "memory_chunks", type_="check")
    op.drop_constraint(
        "ck_ingestion_events_occurred_at_provenance", "ingestion_events", type_="check"
    )
